### ISSUE TITLE
Power Condition Transitions log page is incorrectly decoded

### ISSUE THREAD

**Issue by guorzhen** [hreinecke/sg3_utils#1]
Parameter codes used to decode PCT log page in src/sg_logs.c seem to contradict SCSI spec:
0000h -> active
0001h -> idle_a
0002h -> idle_b
0003h -> idle_c

SPC-4, Revision 37a, Table 399:
0001h -> active
0002h -> idle_a
0003h -> idle_b
0004h -> idle_c

**Comment by hreinecke** [comment]
Resolved with a patch in branch 'for-upstream'.
