### ISSUE TITLE
power condition  is  not good in sg_logs.c

### ISSUE THREAD

**Issue by banxianxie** [hreinecke/sg3_utils#27]
in below function , according to spec, power condition starts from zero ,not from 1. zero stands for active
====== 
static bool
show_power_condition_transitions_page(const uint8_t * resp, int len,
                                      const struct opts_t * op)
{
    int num, pl, pc;
    const uint8_t * bp;
    char str[PCB_STR_LEN];

    if (op->verbose || ((! op->do_raw) && (0 == op->do_hex)))
        printf("Power condition transitions page  [0x1a]\n");
    num = len - 4;
    bp = &resp[0] + 4;
    while (num > 3) {
        pc = sg_get_unaligned_be16(bp + 0);
        pl = bp[3] + 4;
        if (op->filter_given) {
            if (pc != op->filter)
                goto skip;
            if (op->do_raw) {
                dStrRaw(bp, pl);
                break;
            } else if (op->do_hex) {
                hex2stdout(bp, pl, ((1 == op->do_hex) ? 1 : -1));
                break;
            }
        }
        **switch (pc) {
        case 1:**  // banxianxie   here is not accurate

printf("  Accumulated transitions to active"); break;

**Comment by doug-gilbert** [comment]
Not in the spec that I'm working from. Namely spc5r19.pdf table 383 at the top of page 533. It lists parameter codes 1, 2, 3, 4, 8, 9 and says all others are reserved which includes 0.

**Comment by banxianxie** [comment]
sorry, I made a mistake . 
The code   in  sg3_utils-1.42-1.src  is not accurate.  The newest code doesn't have this  issue

**Comment by hreinecke** [comment]
So it's closed.
