### ISSUE TITLE
rescan-scsi-bus.sh --luns=<lun #> prints existing LUNs instead of scanning the LUN specified

### ISSUE THREAD

**Issue by sriemer** [hreinecke/sg3_utils#3]
We have a customer report that the `rescan-scsi-bus.sh` script behavior changed from v1.35 to v1.40 regarding the `rescan-scsi-bus.sh --luns=<lun #>` command. Also latest master (2016-05-17, 2e5c1493fe0d5f96d7b97375686e8fc154e081f6) is affected.

The expected behavior is that only the LUN specified is scanned at already existing SCSI hosts but it prints all existing LUNs instead and doesn't scan anything (verified with `set -x`). The command `rescan-scsi-bus.sh --luns=<lun #> -a` works as expected instead but also scans the specified LUN at not existing SCSI hosts.

The old behavior with v1.35 is that it behaves like the `-a` option is always set.

Should the expected behavior of scanning only the specified LUN at only existing SCSI hosts be implemented?

New behavior output:
````
node02:~ # rescan-scsi-bus.sh --luns=1
Scanning SCSI subsystem for new devices
Scanning host 0 for  SCSI target IDs  0 1 2 3 4 5 6 7, LUNs  1
Scanning host 1 for  SCSI target IDs  0 1 2 3 4 5 6 7, LUNs  1
Scanning host 2 for  SCSI target IDs  0 1 2 3 4 5 6 7, LUNs  1
 Scanning for device 2 0 0 0 ... 
OLD: Host: scsi2 Channel: 00 Id: 00 Lun: 00
      Vendor: IET      Model: VIRTUAL-DISK     Rev: 0   
      Type:   Direct-Access                    ANSI SCSI revision: 04
 Scanning for device 2 0 0 1 ... 
OLD: Host: scsi2 Channel: 00 Id: 00 Lun: 01
      Vendor: IET      Model: VIRTUAL-DISK     Rev: 0   
      Type:   Direct-Access                    ANSI SCSI revision: 04
 Scanning for device 2 0 0 2 ... 
OLD: Host: scsi2 Channel: 00 Id: 00 Lun: 02
      Vendor: IET      Model: VIRTUAL-DISK     Rev: 0   
      Type:   Direct-Access                    ANSI SCSI revision: 04
0 new or changed device(s) found.          
0 remapped or resized device(s) found.
0 device(s) removed.
````

Old behavior output:
````
node02:~ # rescan-scsi-bus.sh --luns=1
Scanning SCSI subsystem for new devices
Scanning host 0 for  SCSI target IDs  0 1 2 3 4 5 6 7, LUNs  1
Scanning host 1 for  SCSI target IDs  0 1 2 3 4 5 6 7, LUNs  1
Scanning host 2 for  SCSI target IDs  0 1 2 3 4 5 6 7, LUNs  1
 Scanning for device 2 0 0 1 ... 
OLD: Host: scsi2 Channel: 00 Id: 00 Lun: 01
      Vendor: IET      Model: VIRTUAL-DISK     Rev: 0   
      Type:   Direct-Access                    ANSI SCSI revision: 04
0 new or changed device(s) found.          
0 remapped or resized device(s) found.
0 device(s) removed.
````

**Comment by hreinecke** [comment]
Indeed, looks like the original output was correct.
So send a fix :-)

**Comment by sriemer** [comment]
Merge requests submitted to SLE-11 SP4, SLE-12 GA, SLE-12-SP1 and SLE-12-SP2.
This is just a mirror. So closing.
