### ISSUE TITLE
RAID controller pass-through

### ISSUE THREAD

**Issue by depeele** [hreinecke/sg3_utils#41]
We would like to make use of sg3_utils, but our disks are behind a RAID controller.

It would be nice if sg3_utils had the ability to reach behind a RAID controller, similar to [smartmontools](https://www.smartmontools.org).

smartmontools does this by allowing the user to specify the type of RAID controller (limited to a few common types), and then uses `ioctl()` calls directly to the controller, invoking SCSI passthrough to allow sending SCSI commands and receiving SCSI results directly to/from the connected disks. 

The downside to smartmontools for our needs is its focus on SMART-related queries without the rich SCSI understanding of sg3_utils.

Thanks in advance for considering this feature request.

**Comment by hreinecke** [comment]
That would depend on the RAID controller.
Some controllers (eg aacraid) expose the internal disks to the OS, but do no attach a disk device to them. For those it would be trivial to use sg3_utils.
Others (like megaraid or hpsa) hide the disks internally, and only expose the resulting disk to the OS.
For those it'll be tricky to do, as we'd have to use internal ioctls to get to those disks.
Which RAID controller do you use?

**Comment by depeele** [comment]
We're using the megaraid controller.

**Comment by doug-gilbert** [comment]
smartmontools has a megaraid pass-through. I'm the maintainer of the SCSI subsystem in smartmontools (and the author of sg3_utils). So SCSI subsystem code in both is remarkably similar. I could probably sue myself :-) If you can program in C then you might be able to do a little "cut and paste". If not I might discuss with the technical lead (Christian Franke) about a little additional utility in smartmontools to facilitate using its pass-throughs (for my pass-through).

**Comment by Austpool** [comment]
Hello.
digging up a slightly old issue, but, i have an Adaptec 5805 controller that doesn't seam to be passing drives thru. it sees then in the bios tools, but marks them as unusable. Once i boot to ubuntu, the drives are not there when i run sg-scan -i .

i'll be trying another controller later (dell perc700, i think), but is it there a trick to getting the adaptec to let the drive thru?
the 5805 has the latest firmware from Adaptec, but the card is actually a Sun card flashed with the generic firmware. done by many and seames to work fine. The sun firmware is behind a paywall, so no updated there.

**Comment by hreinecke** [comment]
Well, that will be tricky.
This is an aacraid controller, which will hide the SCSI drives behind the firmware. Some models have the ability to expose the physical devices (there is the module option 'expose_physical'), but I'm not sure if you can put the controller into jbod mode.

**Comment by Austpool** [comment]
Yeah. i did a lot more digging and found my answer on google. 
Time to find the right controller cheap and set it up for the job.

however, the latest firmware for the 5805 adds JBOD as an option, but it still wont allow me to add those drives in as JBOD without fixing the formatting first. The drives are visible in the cards bios screen, but can not be used in any way.

**Comment by hreinecke** [comment]
Nothing we can do here :-(
