### ISSUE TITLE
1.45?

### ISSUE THREAD

**Issue by kloczek** [hreinecke/sg3_utils#53]
http://sg.danny.cz/sg/sg3_utils.html says that latest version is 1.45 but there is no here that tagged version.

Could you please update?

**Comment by doug-gilbert** [comment]
In the meantime this tarball: http://sg.danny.cz/sg/p/gh_sg3_patches_rev832_release145.tgz contains a 13 part patchset that when applied to this repo (e.g. with 'git am <dir>/*.patch') should bring your copy to release version 1.45 .

**Comment by kloczek** [comment]
That is OK :)

What about updating content of that repo using those patches?

**Comment by kloczek** [comment]
Still no `1.45` git tag in repo :(

**Comment by kloczek** [comment]
You know .. in the one and half of the mont it is possible to deliver that git tag using even pigin ;)

My automation is using for sg3_utils package is using autogenerated from git tags tar balls. Please add release tag 🙏

**Comment by hreinecke** [comment]
Tagged git-svn 844 with 'v1.45'.
