### ISSUE TITLE
Is it possible to clone a 520 or 526 or 528 bytes per sector to disk image file?

### ISSUE THREAD

**Issue by rcorsari** [hreinecke/sg3_utils#59]
Hello sorry
I have searched for a mailing list about sg3_utils but can't find one

So excuse me to write here

I have plugged some SAS drives to my UBUNTU 18 to clone them with destination image file like disk00.bin or disk01.dsk

With a simulation like sg_format I have detected that the drives are 528 bytes per sector

Well is there any of sg_xxx utils that does allow to clone the drive

Thank you
Robert

**Comment by doug-gilbert** [comment]
Don't know about 520 and 526 but 528 byte sectors sound like 512 byte logical block size plus 16 bytes of protection information (PI) per the T10 specs. Have a look at my ddpt utility (in a package of the same name). Look at the [protect=RDP[,WRP]] operand. It follows the SBC-3 (and 4) specs. Make sure to set 'bs=512' and you can leave bpt= at its default of 128. By default (i.e. without setting protect= to a non-zero value) only the logical block data (i.e. without the 16 byte PI per block) will be copied to the output.

sg_dd will clone a disk (without PI if PI was present). sg_readcap will show you if PI is present (and what type it is).

**Comment by yemencit** [comment]
![217079A5-870D-479A-837E-7F7D757B8657](https://user-images.githubusercontent.com/110853032/183769804-cc098455-2299-47c0-b49c-b4352d04d55b.jpeg)
I have this problem need format this hard disk from 528 to 512 but can't note this is hard disk ibm working flash ssd 0kb

**Comment by hreinecke** [comment]
You are not cloning, you are reformatting the drive. Which is tricky at best, and might not work if the drive already _is_ at 528 byte sector size; after all, there's a fair chance the drive firmware uses the additional space on each sector, in which case reformatting would make the drive unusable.
Don't.
