### ISSUE TITLE
1.45 is missing

### ISSUE THREAD

**Issue by Neustradamus** [hreinecke/sg3_utils#66]
1.45 (20200302) build is missing:
- http://sg.danny.cz/sg/sg3_utils.html

**Comment by doug-gilbert** [comment]
Seems as though Hannes is busy. In the meantime, you could look here: https://github.com/doug-gilbert/sg3_utils/tree/master/trunk or here: https://github.com/doug-gilbert/sg3_utils/tree/master/tags for the tags.

**Comment by doug-gilbert** [comment]
I just deleted the https://github.com/doug-gilbert/sg3_utils repository and replaced it with the same thing but without tree/master/trunk stuff. And that repo has branches and (git) tags back to release 1.20. You might even notice there is a branch and tag for release 1.46 .

**Comment by hreinecke** [comment]
Tagged git-svn id 844 with 'v1.45'.

**Comment by Neustradamus** [comment]
@hreinecke: Whaouuu, thanks!

But there are some problems:
- https://github.com/hreinecke/sg3_utils/tags
- https://github.com/hreinecke/sg3_utils/releases/tag/remote
- https://github.com/hreinecke/sg3_utils/releases/tag/r1.46
- https://github.com/hreinecke/sg3_utils/releases/tag/release-1.48 (vs https://github.com/hreinecke/sg3_utils/releases/tag/v1.48)

Can you look?

**Comment by hreinecke** [comment]
Fixed now.

**Comment by Neustradamus** [comment]
@hreinecke: Thanks, there is always: r1.46 vs v1.46
