### ISSUE TITLE
sg3_utils version/release 1.48 available

### ISSUE THREAD

**Issue by doug-gilbert** [hreinecke/sg3_utils#96]
This is not an issue. Version 1.48 of sg3_utils was released on 1 August 2023 and is available at https://github.com/doug-gilbert/sg3_utils and maybe here in the near future. Only minor problems with the Android port have been reported (and fixed) since the release.

**Comment by mwilck** [comment]
@doug-gilbert, I am aware of your update. The openSUSE mirror + code is now maintained in openSUSE/sg3_utils, which is maintained by multiple engineers.

**Comment by hreinecke** [comment]
Updated repository to git-svn 1046.
